name: ToEconomy
main: com.toplugins.toeconomy.Main
version: 1.0.5
author: ooliveirasdev

softdepend: [Vault]

commands:

  money:
    description: Comando principal de economia
    usage: /money [definir|adicionar|diminuir] <player> <valor>
    aliases: [dinheiro, reais]
  pay:
    description: Envia dinheiro para outro jogador
    usage: /pay <player> <valor>
    aliases: [pagar, transferir, pix]

permissions:
  toeconomy.basic:
    description: Permite usar comandos de nível básico
    default: true

  toeconomy.admin:
    description: Permissões administrativas de economia
    default: op

